### PR TITLE
Add property tests

### PR DESCRIPTION
**Pull request by waisbrot**
I don't know that this actually _solves_ #4, but I wanted to try learning property tests and this is what I ended up with.

Overall, I liked it. I can run the tests with rebar3:
```
rebar3 proper
```
it accepts a `--cover` flag to collect coverage data. Running PropEr tests and understanding failures is pretty easy.

The part I found difficult was generating tests that were not trivial and didn't involve re-inventing the iso8601 library in the test code. I'm not sure how well I did there.

### CODE REVIEW

**Comment by oubiwann** [comment]
I haven’t looked at the Travis error for this, but if you can get that fixed (and make sure these new tests are run by Travis), I’d be willing to merge your change.

**Comment by oubiwann** [comment]
Hrm, all are failing now; the Travis errors give no info. You might have to `DEBUG=1` ...

**Comment by waisbrot** [comment]
Sorry I haven't been touching this. The problem is that OTP < 18 can't run PropEr tests (at least, not using the Rebar3 plugin and code that I supply here). Getting Travis to do the right thing is usually a lengthy process of trial and error for me, but I do plan on coming back to this when I'm less busy elsewhere.

**Comment by oubiwann** [comment]
heads up on this -- we're going to follow rebar3's approach, and only actively test Erlang 19+ ...

**Pull request closed without merging**
