### PR TITLE
Be stricter on static analysis (via dialyzer)

### LINKED ISSUE #55: This library uses types that are not exported by Erlang's calendar module
In  particular, when running dialyzer, these warnings are generated:

```
   0: Unknown type calendar:hour/0
   0: Unknown type calendar:minute/0
   0: Unknown type calendar:second/0
```

Looking at `calendar.er`, it seems that only the following types are exported:

```
-export_type([date/0, time/0, datetime/0, datetime1970/0]).
```

Might have to just redefine `calendar`'s private types in this lib ...

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
[edited original description]

Added more to the dialyzer config.

### CODE REVIEW

**Comment by oubiwann** [comment]
Could you update / rebase?  I only added `unknown` -- you added more:
```erlang
    {warnings, [
        unknown,
        unmatched_returns,
        error_handling,
        underspecs
    ]}
```

Would love to see this contribution come in 😄

**Comment by oubiwann** [comment]
Oh, hey -- I also have incorrect verb agreement here:
* https://github.com/erlsci/iso8601/commit/94c642c10991f27a68f8770a2179c195b1f7afcf

Could you change this:
```
 %% This group of types are from calendar.erl; we need to use some of them 
```
To this?
```
 %% This group of types is from calendar.erl; we need to use some of them 
```

**Comment by paulo-ferraz-oliveira** [comment]
Sure. Give me a few minutes.

**Comment by paulo-ferraz-oliveira** [comment]
Done and done.

**Comment by paulo-ferraz-oliveira** [comment]
Wait, something's off here. I didn't change that many files. Must've something to do with the renaming of branch `master`.

**Comment by oubiwann** [comment]
Yay! Looks like you got it fixed :-) 

Thanks a bunch!

**Pull request merged**
