### PR TITLE
Support iso8601 durations

### PR DESCRIPTION
**Pull request by rjcoelho**
Implementation is taken from https://github.com/sl45sms/erlang_iso8601

### CODE REVIEW

**Comment by oubiwann** [comment]
Been meaning to merge this for a while — thanks!

**Comment by rjcoelho** [comment]
Can you tag a release ? thanks!

**Comment by oubiwann** [comment]
Yup. Waiting on one more PR to be fixed; if they don’t respond in the next day or two, I’ll release as-is.

**Comment by oubiwann** [comment]
I've released 1.3 with the latest merges. (That'll get bumped to 1.3.1 when the current open PR gets merged.)

**Pull request merged**
