### PR TITLE
Fix typespecs for Erlang 18.x

### PR DESCRIPTION
**Pull request by mentels**

### CODE REVIEW

**Comment by arjan** [comment]
bump?

**Comment by wk8** [comment]
Just a heads up that there's a maintained fork of this repo at : https://github.com/wk8/erlang_iso8601 :)

**Comment by oubiwann** [comment]
The original project has a new maintainer and a new home:

* https://github.com/erlsci/iso8601

Old links to the original repo will redirect to the new home -- both in the browser and via the cli.

That being said, most (all?) of this work has been merged in other branches. If there are still changes you'd like to make, however, you'll need to rebase.

I'll leave this open for a while, in case that's what you want to do :-)

**Comment by oubiwann** [comment]
I've updated the conflicts here and merged the branch.

Thanks!

**Pull request merged**
