### PR TITLE
Add new fun to parse durations 

### PR DESCRIPTION
**Pull request by sl45sms**
http://en.wikipedia.org/wiki/ISO_8601#Durations
may help for Time intervals

### CODE REVIEW

**Comment by wk8** [comment]
Just a heads up that there's a maintained fork of this repo at : https://github.com/wk8/erlang_iso8601 :)

**Comment by oubiwann** [comment]
The original project has a new maintainer and a new home:
 * https://github.com/erlsci/iso8601

Old links to the original repo will redirect to the new home -- both in the browser and via the cli.

**Comment by oubiwann** [comment]
@sl45sms If you'd like to see your changes make it into the repo, could you rebase your branch against master and re-push to your fork?

Thanks!

**Comment by oubiwann** [comment]
This PR is several years old, and there's been no response, so I'm going to close it. However! Feel free to reopen if you want to come back to it!

If you do want to get this merged, it will have an easier time of getting accepted if the different types of changes go into their own PRs:
 * one for the feature
 * one for the docs
 * one for the `Makefile`

Honestly, though, the last two are less likely to get merged (though I could probably be talked into a `Makefile` which provides users a means of easily generating the docs ...).

**Pull request closed without merging**
