### PR TITLE
erlang.mk compatibility

### PR DESCRIPTION
**Pull request by qrilka**
Empty "modules" in iso8601.app.src + removed ebin.
It was not clear why do you have ebin in the repository

### CODE REVIEW

**Comment by oubiwann** [comment]
@qrilka I don't use erlang.mk ... but your change implies that erlang.mk doesn't work when modules are defined in app.src? (I ask because these seems odd to me ...)

**Comment by oubiwann** [comment]
@lukebakken Per the note in #15 (which was closed as a duplicate), some thoughts:

* +1 for removing the app.src file in ``./ebin`` (that's been done now)
* -1 for making ``modules`` empty -- this will break other tools

It's been a couple of years since erlang.mk came out, now ... does this still need to be done?

If so, we need to find a way to support erlang.mk that doesn't impact other tools.

**Comment by qrilka** [comment]
I don't have a context of this PR in my mind anymore and there were some changes in `erlang.mk` and I  haven't used it (`erlang.mk`) for a couple of years already.
I don't use Erlang lately so feel free to go the way you want about this ticket.

**Comment by oubiwann** [comment]
@qrilka Thanks for writing back! Sorry it took us so long to respond :-(

I've since created a help-wanted ticket for this, so I will close this PR allowing another contributor to work on just what's necessary.

Thanks again!

**Pull request closed without merging**
