### PR TITLE
Rename `maybe` type to `undefined_or` to avoid clashing with maybe stm in OTP27

### PR DESCRIPTION
**Pull request by asakura**
subj

### CODE REVIEW

**Comment by nixxquality** [comment]
OTP27 released yesterday, would be nice to see this merged :)

**Comment by cocoa-xu** [comment]
Hi thanks for the great library! Just had the same issue when compiling a library depends on this one:

```
===> Analyzing applications...
===> Compiling iso8601
===> Compiling src/iso8601.erl failed
src/iso8601.erl:38:16: syntax error before: '::'
src/iso8601.erl:367:18: syntax error before: 'maybe'
```

It'd be great to see this merged. :)

**Comment by dsrosario** [comment]
@oubiwann, is it possible to have a release with this PR, please?

**Comment by oubiwann** [comment]
Oh no, I never saw this! Sorry everyone!!! :-(((( Reviewing now ... will merge and re-release ASAP.

**Review by oubiwann — APPROVED** [review]
Thank you!

**Pull request merged**
